// react-project/src/pages/CartComponent.js
import { useState, useEffect } from "react";

export default function CartComponent({ userId }) {
  const [cartItems, setCartItems] = useState([]);

  useEffect(() => {
    fetch(`http://localhost:3001/api/cart?userId=${userId}`)
      .then((res) => res.json())
      .then((cartData) => {
        const grouped = {};
        cartData.forEach((item) => {
          if (!grouped[item.product_id]) {
            grouped[item.product_id] = { ...item, quantity: 1 };
          } else {
            grouped[item.product_id].quantity += 1;
          }
        });

        const groupedItems = Object.values(grouped);

        const productDetailsPromises = groupedItems.map((item) =>
          fetch(`http://localhost:3001/api/product/${item.product_id}`)
            .then((res) => res.json())
            .then((productData) => {
              const product = productData[0];
              return {
                ...item,
                productName: product.name,
                price: product.price,
              };
            })
        );

        Promise.all(productDetailsPromises).then((enrichedItems) => {
          setCartItems(enrichedItems);
        });
      });
  }, [userId]);

  return (
    <div>
      {cartItems.map((item, index) => (
        <div key={index}>
          <h3>{item.productName}</h3>
          <p>${item.price}</p>
          <p>Quantity: {item.quantity}</p>
          <hr />
        </div>
      ))}
    </div>
  );
}

// web-components/src/components/cart-component.js
import { CartService } from "../services/cart-service.js";
import { getUserId } from "../auth-util.js";

class CartComponent extends HTMLElement {
  constructor() {
    super();
    this.attachShadow({ mode: "open" });
    this.cartService = new CartService();
  }

  connectedCallback() {
    this.userId = getUserId();
    this.render();
  }

  async render() {
    this.userId = getUserId();
    if (!this.userId) return;

    const cart = await this.cartService.fetchCart(this.userId);

    const groupedItems = cart.reduce((acc, item) => {
      if (!acc[item.product_id]) {
        acc[item.product_id] = { ...item, quantity: 1 };
      } else {
        acc[item.product_id].quantity += 1;
      }
      return acc;
    }, {});

    const enrichedCartItems = await Promise.all(
      Object.values(groupedItems).map(async (item) => {
        const productDetails = await this.fetchProductDetails(item.product_id);
        return {
          ...item,
          productName: productDetails.name,
          description: productDetails.description,
          price: productDetails.price,
        };
      })
    );

    const isCheckoutPage = this.getAttribute("data-page") === "checkout";

    this.shadowRoot.innerHTML = `
        <div>
            ${!isCheckoutPage ? `<h1>Cart</h1>` : ""}
            <div id="cart-items"></div>
            ${
              !isCheckoutPage
                ? `
            <button id="go-to-products">Go to Products</button>
            <button id="go-to-checkout">Go to Checkout</button>
            `
                : ""
            }
        </div>
    `;

    const cartList = this.shadowRoot.querySelector("#cart-items");
    enrichedCartItems.forEach((item) => {
      const itemDiv = document.createElement("div");
      itemDiv.innerHTML = `
        <h3>${item.productName}</h3>
        <p>$${item.price}</p>
        <p>Quantity: ${item.quantity}</p>
        <hr/>
      `;
      cartList.appendChild(itemDiv);
    });

    if (!isCheckoutPage) {
      this.shadowRoot
        .querySelector("#go-to-products")
        .addEventListener("click", () => {
          window.navigateTo("/products");
        });

      this.shadowRoot
        .querySelector("#go-to-checkout")
        .addEventListener("click", () => {
          window.navigateTo("/checkout");
        });
    }
  }

  async fetchProductDetails(productId) {
    const response = await fetch(
      `http://localhost:3001/api/product/${productId}`
    );
    if (!response.ok) {
      throw new Error(`Failed to fetch product ${productId}`);
    }
    const productArray = await response.json();
    return productArray[0];
  }
}

customElements.define("cart-component", CartComponent);
