// web-components/src/components/product-list-component.js
import { ProductService } from "../services/product-service.js";

class ProductList extends HTMLElement {
  constructor() {
    super();
    this.attachShadow({ mode: "open" });
    this.productService = new ProductService();
  }
  connectedCallback() {
    this.render();
  }
  render() {
    this.shadowRoot.innerHTML = `
      <div>
        <h1>Product List</h1>
        <ul id="products"></ul>
        <div>
          <button id="go-to-cart">Go to Cart</button>
          <button id="go-to-checkout">Go to Checkout</button>
        </div>
      </div>
    `;
    this.fetchProducts();
    this.addNavigationListeners();
  }

  async fetchProducts() {
      const products = await this.productService.fetchProducts();
      const productsList = this.shadowRoot.querySelector('#products');
      products.forEach(product => {
        const li = document.createElement('li');
        li.innerHTML = `
          <div>
            <p>${product.name}</p>
            <p>${product.description}</p>
            <p>${product.price}</p>
            <button>Add to Cart</button>
          </div>
        `;
        productsList.appendChild(li);
      });
      this.shadowRoot.querySelectorAll('.add-to-cart').forEach(button => {
        button.addEventListener('click', (event) => this.addToCart(event));
      });
  }

  addNavigationListeners() {
    this.shadowRoot.querySelector('#go-to-cart').addEventListener('click', () => {
      window.navigateTo('/cart');
    });

    this.shadowRoot.querySelector('#go-to-checkout').addEventListener('click', () => {
      window.navigateTo('/checkout');
    });
  }

  async addToCart(event) {
    const productId = event.target.getAttribute('data-id');
    const userId = 'df992ef6-af8d-4d4d-8f50-1214b7520dcf';
    const product = { userId, productId, quantity: 1 };
    await this.productService.addProductToCart(product);
  }
}

customElements.define('product-list', ProductList);

// react-project/src/pages/ProductList.js
import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";

export default function ProductList() {
  const navigate = useNavigate();
  const [products, setProducts] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch("http://localhost:3001/api/products")
      .then((res) => res.json())
      .then((data) => {
        setProducts(data);
        setLoading(false);
      });
  }, []);

  const addToCart = (productId) => {
    const userId = "df992ef6-af8d-4d4d-8f50-1214b7520dcf";
    const quantity = 1;

    fetch("http://localhost:3001/api/cart/add", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        userId,
        productId,
        quantity,
      }),
    });
  };

  if (loading) return <p>Loading product...</p>;

  return (
    <div>
      <h1>Product List</h1>
      <ul>
        {products.map((product) => (
          <li key={product.id}>
            <div>
              <p>{product.name}</p>
              <p>{product.description}</p>
              <p>${product.price}</p>
              <button onClick={() => addToCart(product.id)}>Add to Cart</button>
            </div>
          </li>
        ))}
      </ul>
      <div>
        <button onClick={() => navigate("/cart")}>Go to Cart</button>
        <button onClick={() => navigate("/checkout")}>Go to Checkout</button>
      </div>
    </div>
  );
}
