// react-project/src/pages/Cart.js
import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';

export default function Cart() {
    const navigate = useNavigate();
    const [cartItems, setCartItems] = useState([]);
    const userId = 'df992ef6-af8d-4d4d-8f50-1214b7520dcf';

    useEffect(() => {
        fetch(`http://localhost:3001/api/cart?userId=${userId}`)
            .then((res) => res.json())
            .then((cartData) => {
                console.log('Cart data:', cartData); 

                const productDetailsPromises = cartData.map((item) =>
                    fetch(`http://localhost:3001/api/product/${item.product_id}`)
                        .then((res) => res.json())
                        .then((productData) => {
                            console.log('Product data:', productData); 
                            const product = productData[0]; 
                            item.productName = product.name;
                            item.price = product.price;
                            return item;
                        })
                );

                Promise.all(productDetailsPromises).then((updatedCartItems) => {
                    console.log('Updated cart items:', updatedCartItems); 
                    setCartItems(updatedCartItems);
                });
            });
    }, []);

    return (
        <div>
            <h2>Cart</h2>
            {cartItems.map((item) => (
                <div key={item.id}>
                    <h3>{item.productName}</h3>
                    <p>${item.price}</p>
                    <p>Quantity: {item.quantity}</p>
                </div>
            ))}
            <button onClick={() => navigate('/products')}>Go to Products</button>
            <button onClick={() => navigate('/checkout')}>Go to Checkout</button>
        </div>
    );
}

// Angular/src/app/cart/cart.component.ts
import { Component, OnInit } from '@angular/core';
import { SupabaseService } from '../supabase.service';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';

@Component({
  selector: 'app-cart',
  imports: [CommonModule],
  templateUrl: './cart.component.html',
  styleUrl: './cart.component.css'
})
export class CartComponent implements OnInit {
  cartItems: any[] = [];
  readonly userId = 'df992ef6-af8d-4d4d-8f50-1214b7520dcf';
  private router: Router;

  constructor(private supabaseService: SupabaseService, router : Router ) {
    this.router = router;
  }

  ngOnInit() {
    this.supabaseService.getCart(this.userId).subscribe((items: any) => {
      this.cartItems = items;
      this.cartItems.forEach(item => {
        this.supabaseService.getProductById(item.product_id).subscribe((products: any) => {
          const product = products[0];
          item.productName = product.name;
        });
      });
    });
  }

  goToCheckout() {
    this.router.navigate(['/checkout']);
  }
  goToProducts() {  
    this.router.navigate(['/products']);
  }
}
<h2>Your Cart</h2>

<div *ngIf="cartItems.length > 0; else emptyCart">
    <ul>
        <li *ngFor="let item of cartItems">
            Product Name: {{ item.productName }} - Quantity: {{ item.quantity }}
        </li>
    </ul>
</div>

<ng-template #emptyCart>
    <p>Your cart is empty.</p>
</ng-template>

<button type="button" (click)="goToProducts()">Products</button>
<button type="button" (click)="goToCheckout()">Checkout</button>
