// react-project/src/pages/Checkout.js
import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';

export default function Checkout() {
    const navigate = useNavigate();
    const [cartItems, setCartItems] = useState([]);
    const [totalPrice, setTotalPrice] = useState(0);
    const userId = 'df992ef6-af8d-4d4d-8f50-1214b7520dcf';

    useEffect(() => {
        fetch(`http://localhost:3001/api/cart?userId=${userId}`)
        .then((res) => res.json())
        .then((cartData) => {
            const productDetailsPromises = cartData.map((item) =>
                fetch(`http://localhost:3001/api/product/${item.product_id}`)
                    .then((res) => res.json())
                    .then((productData) => {
                        const product = productData[0]; 
                        item.productName = product.name;
                        item.price = product.price;
                        return item;
                    })
            );

            Promise.all(productDetailsPromises).then((updatedCartItems) => {
                console.log('Updated cart items:', updatedCartItems); 
                setCartItems(updatedCartItems);
                const total = updatedCartItems.reduce((sum, item) => sum + item.price * item.quantity, 0);
                setTotalPrice(total);
            });
        });
    }, []);

    return (
        <div>
            <h2>Checkout</h2>
            {cartItems.map((item) => (
                <div key={item.id}>
                    <h3>{item.productName}</h3>
                    <p>${item.price}</p>
                    <p>Quantity: {item.quantity}</p>
                </div>
            ))}
            <h3>Total: ${totalPrice.toFixed(2)}</h3>
            <button onClick={() => navigate('/products')}>Go to Products</button>
            <button onClick={() => navigate('/cart')}>Go to Cart</button>
            <section className="payment-info">
                <h2>Payment Information</h2>
                <div>
                    <label htmlFor="cardNumber">Card Number</label>
                    <input type="text" id="cardNumber" value="1234 5678 9012 3456" readOnly />
                </div>
                <div>
                    <label htmlFor="expiryDate">Expiry Date</label>
                    <input type="month" id="expiryDate" value="2025-12" readOnly />
                </div>
                <div>
                    <label htmlFor="cvv">CVV</label>
                    <input type="text" id="cvv" value="123" readOnly />
                </div>
            </section>
            <div className="checkout-button">
                <button>Proceed to Payment</button>
            </div>
        </div>
    );
}

// Angular/src/app/checkout/checkout.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { SupabaseService } from '../supabase.service';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-checkout',
  imports: [CommonModule],
  templateUrl: './checkout.component.html',
  styleUrl: './checkout.component.css'
})
export class CheckoutComponent {
cartItems: any[] = [];
totalAmount: number = 0;
readonly userId = 'df992ef6-af8d-4d4d-8f50-1214b7520dcf';
private router: Router;

  constructor(router: Router, private supabaseService: SupabaseService) {
    this.router = router;
  }
  
  ngOnInit() {
    this.supabaseService.getCart(this.userId).subscribe((items: any) => {
      this.cartItems = items;
      this.cartItems.forEach(item => {
        this.supabaseService.getProductById(item.product_id).subscribe((product: any) => {
          item.productName = product[0].name;
          item.price = product[0].price;
          this.totalAmount += item.price;
        });
      });
    });
  }

  goToCart() { 
    this.router.navigate(['/cart']);
  }
  goToProducts() { 
    this.router.navigate(['/products']);
  }
}


<div class="checkout-container">
    <h1>Checkout</h1>
  
    <section class="order-summary">
      <h2>Order Summary</h2>
      <ul>
        <li *ngFor="let item of cartItems">
          <p>{{ item.productName }} - ${{ item.price }}</p>
        </li>
      </ul>
      <p>Total: ${{ totalAmount }}</p>
    </section>
  
    <section class="payment-info">
      <h2>Payment Information</h2>
      <div>
        <label for="cardNumber">Card Number</label>
        <input type="text" id="cardNumber" value="1234 5678 9012 3456" readonly>
      </div>
      <div>
        <label for="expiryDate">Expiry Date</label>
        <input type="month" id="expiryDate" value="2025-12" readonly>
      </div>
      <div>
        <label for="cvv">CVV</label>
        <input type="text" id="cvv" value="123" readonly>
      </div>
    </section>
  
    <div class="checkout-button">
      <button>Proceed to Payment</button>
    </div>
  </div>

<button type="button" (click)="goToCart()">Cart</button>
<button type="button" (click)="goToProducts()">Products</button>
